export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const LISTINGS_REQUEST = 'LISTINGS_REQUEST';
export const LISTINGS_SUCCESS = 'LISTINGS_SUCCESS';
export const LISTINGS_FAILURE = 'LISTINGS_FAILURE';

export const ALREADY_LOGGED_IN = 'ALREADY_LOGGED_IN';
export const NOT_YET_LOGGED_IN = 'NOT_YET_LOGGED_IN';

export const REGISTER_REQUESTED = 'REGISTER_REQUESTED';
export const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const ADD_LISTING_REQUESTED = 'ADD_LISTING_REQUESTED';
export const ADD_LISTING_SUCCESSFUL = 'ADD_LISTING_SUCCESSFUL';
export const ADD_LISTING_FAILURE = 'ADD_LISTING_FAILURE';

export const EDIT_LISTING_REQUESTED = 'EDIT_LISTING_REQUESTED';
export const EDIT_LISTING_SUCCESSFUL = 'EDIT_LISTING_SUCCESSFUL';
export const EDIT_LISTING_FAILURE = 'EDIT_LISTING_FAILURE';

export const DELETE_LISTING_REQUESTED = 'DELETE_LISTING_REQUESTED';
export const DELETE_LISTING_SUCCESSFUL = 'DELETE_LISTING_SUCCESSFUL';
export const DELETE_LISTING_FAILURE = 'DELETE_LISTING_FAILURE';

export const SEEKER_MATCH_REQUESTED = 'SEEKER_MATCH_REQUESTED';
export const SEEKER_MATCH_SUCCESSFUL = 'SEEKER_MATCH_SUCCESSFUL';
export const SEEKER_MATCH_FAILURE = 'SEEKER_MATCH_FAILURE';

export const GET_SEEKER_MATCHES_REQUESTED = 'GET_SEEKER_MATCHES_REQUESTED';
export const GET_SEEKER_MATCHES_SUCCESSFUL = 'GET_SEEKER_MATCHES_SUCCESSFUL';
export const GET_SEEKER_MATCHES_FAILURE = 'GET_SEEKER_MATCHES_FAILURE';

export const JOB_MATCH_REQUESTED = 'JOB_MATCH_REQUESTED';
export const JOB_MATCH_SUCCESSFUL = 'JOB_MATCH_SUCCESSFUL';
export const JOB_MATCH_FAILURE = 'JOB_MATCH_FAILURE';

export const GET_MATCHES_FOR_JOBS_REQUESTED= 'GET_MATCH_FOR_JOBS_RQUESTED';
export const GET_MATCHES_FOR_JOBS_SUCCESSFUL = 'GET_MATCHES_FOR_JOBS_SUCCESSFUL';
export const GET_MATCHES_FOR_JOBS_FAILURE = 'GET_MATCHES_FOR_JOBS_FAILURE';