export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const LISTINGS_REQUEST = 'LISTINGS_REQUEST';
export const LISTINGS_SUCCESS = 'LISTINGS_SUCCESS';
export const LISTINGS_FAILURE = 'LISTINGS_FAILURE';

export const ALREADY_LOGGED_IN = 'ALREADY_LOGGED_IN';
export const NOT_YET_LOGGED_IN = 'NOT_YET_LOGGED_IN';

export const REGISTER_REQUESTED = 'REGISTER_REQUESTED';
export const REGISTER_SUCCESSFUL = 'REGISTER_SUCCESSFUL';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const ADD_LISTING_REQUESTED = 'ADD_LISTING_REQUESTED';
export const ADD_LISTING_SUCCESSFUL = 'ADD_LISTING_SUCCESSFUL';
export const ADD_LISTING_FAILURE = 'ADD_LISTING_FAILURE';

export const EDIT_LISTING_REQUESTED = 'EDIT_LISTING_REQUESTED';
export const EDIT_LISTING_SUCCESSFUL = 'EDIT_LISTING_SUCCESSFUL';
export const EDIT_LISTING_FAILURE = 'EDIT_LISTING_FAILURE';

export const DELETE_LISTING_REQUESTED = 'DELETE_LISTING_REQUESTED';
export const DELETE_LISTING_SUCCESSFUL = 'DELETE_LISTING_SUCCESSFUL';
export const DELETE_LISTING_FAILURE = 'DELETE_LISTING_FAILURE';

export const MATCH_JOB_WITH_SEEKER_REQUESTED = 'MATCH_JOB_WITH_SEEKER_REQUESTED';
export const MATCH_JOB_WITH_SEEKER_SUCCESSFUL = 'MATCH_JOB_WITH_SEEKER_SUCCESSFUL';
export const MATCH_JOB_WITH_SEEKER_FAILURE = 'MATCH_JOB_WITH_SEEKER_FAILURE';

export const MATCH_SEEKER_WITH_COMPANY_REQUESTED = 'MATCH_SEEKER_WITH_COMPANY_REQUESTED';
export const MATCH_SEEKER_WITH_COMPANY_SUCCESSFUL = 'MATCH_SEEKER_WITH_COMPANY_SUCCESSFUL';
export const MATCH_SEEKER_WITH_COMPANY_FAILURE = 'MATCH_SEEKER_WITH_COMPANY_FAILURE';

export const REJECT_JOB_WITH_SEEKER_REQUESTED = 'REJECT_JOB_WITH_SEEKER_REQUESTED';
export const REJECT_JOB_WITH_SEEKER_SUCCESSFUL = 'REJECT_JOB_WITH_SEEKER_SUCCESSFUL';
export const REJECT_JOB_WITH_SEEKER_FAILURE = 'REJECT_JOB_WITH_SEEKER_FAILURE';

export const REJECT_SEEKER_WITH_COMPANY_REQUESTED = 'REJECT_SEEKER_WITH_COMPANY_REQUESTED';
export const REJECT_SEEKER_WITH_COMPANY_SUCCESSFUL = 'REJECT_SEEKER_WITH_COMPANY_SUCCESSFUL';
export const REJECT_SEEKER_WITH_COMPANY_FAILURE = 'REJECT_SEEKER_WITH_COMPANY_FAILURE';